{{- if and (not .Values.backend.tls.existingSecret) (or .Values.backend.tls.xgtServerCert .Values.backend.tls.proxyClientCert .Values.backend.tls.proxyClientKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.backendTlsSecret" . }}
  labels:
    app: backend
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.backend.tls.xgtServerCert }}
  xgt-server.pem: {{ .Values.backend.tls.xgtServerCert | quote }}
  {{- end }}
  {{- if .Values.backend.tls.proxyClientCert }}
  proxy-client-cert.pem: {{ .Values.backend.tls.proxyClientCert | quote }}
  {{- end }}
  {{- if .Values.backend.tls.proxyClientKey }}
  proxy-client-key.pem: {{ .Values.backend.tls.proxyClientKey | quote }}
  {{- end }}
{{- end }}
