{{- if and (not .Values.backend.oidc.existingSecret) .Values.backend.oidc.clientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.backendOidcSecret" . }}
  labels:
    app: backend
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  MC_OIDC_CLIENT_SECRET: {{ .Values.backend.oidc.clientSecret | quote }}
{{- end }}
{{- if and (not .Values.backend.oidc.caCertExistingSecret) .Values.backend.oidc.caCert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.backendOidcCaSecret" . }}
  labels:
    app: backend
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  oidc-ca.pem: {{ .Values.backend.oidc.caCert | quote }}
{{- end }}
