{{- if and (not .Values.frontend.tls.existingSecret) (or .Values.frontend.tls.publicCert .Values.frontend.tls.privateKey .Values.frontend.tls.certChain) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.frontendTlsSecret" . }}
  labels:
    app: frontend
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.frontend.tls.publicCert }}
  public.pem: {{ .Values.frontend.tls.publicCert | quote }}
  {{- end }}
  {{- if .Values.frontend.tls.privateKey }}
  private.pem: {{ .Values.frontend.tls.privateKey | quote }}
  {{- end }}
  {{- if .Values.frontend.tls.certChain }}
  chain.pem: {{ .Values.frontend.tls.certChain | quote }}
  {{- end }}
{{- end }}
