{{- if and .Values.xgt.licenseManager.enabled .Values.xgt.licenseManager.licenseFiles.data (not .Values.xgt.licenseManager.licenseFiles.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.licenseManagerLicenseSecret" . }}
  labels:
    app: xgt-license-manager
    {{- include "rocketgraph.labels" . | nindent 4 }}
stringData:
  {{- range $name, $content := .Values.xgt.licenseManager.licenseFiles.data }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
