{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rocketgraph.fullname.mongodb" . }}
  labels:
    app: mongodb
    {{- include "rocketgraph.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.mongodb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.openshift.enabled }}
      serviceAccountName: {{ include "rocketgraph.fullname.serviceaccount" . }}
      {{- end }}
      {{- with .Values.mongodb.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          {{- with .Values.mongodb.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.mongodb.auth.enabled }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "rocketgraph.mongodbAuthSecret" . }}
                  key: mongodb-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rocketgraph.mongodbAuthSecret" . }}
                  key: mongodb-root-password
          {{- end }}
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          readinessProbe:
            exec:
              command:
                {{- if .Values.mongodb.auth.enabled }}
                - mongosh
                - -u
                - $(MONGO_INITDB_ROOT_USERNAME)
                - -p
                - $(MONGO_INITDB_ROOT_PASSWORD)
                - --authenticationDatabase
                - admin
                - --eval
                - "db.adminCommand('ping')"
                {{- else }}
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
                {{- end }}
            periodSeconds: {{ .Values.mongodb.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mongodb.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.mongodb.readinessProbe.failureThreshold }}
          livenessProbe:
            exec:
              command:
                {{- if .Values.mongodb.auth.enabled }}
                - mongosh
                - -u
                - $(MONGO_INITDB_ROOT_USERNAME)
                - -p
                - $(MONGO_INITDB_ROOT_PASSWORD)
                - --authenticationDatabase
                - admin
                - --eval
                - "db.adminCommand('ping')"
                {{- else }}
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
                {{- end }}
            initialDelaySeconds: {{ .Values.mongodb.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mongodb.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mongodb.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.mongodb.livenessProbe.failureThreshold }}
          {{- with .Values.mongodb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      {{- with .Values.mongodb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.persistence.existingClaim | default (printf "%s-mongodb-data" .Release.Name) }}
{{- end }}
