{{- if and .Values.mongodb.tls.enabled (not .Values.mongodb.tls.existingSecret) (or .Values.mongodb.tls.cert .Values.mongodb.tls.key .Values.mongodb.tls.caCert .Values.mongodb.tls.clientCert .Values.mongodb.tls.clientKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.mongodbTlsSecret" . }}
  labels:
    app: mongodb
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if or .Values.mongodb.tls.cert .Values.mongodb.tls.key }}
  server.pem: |
    {{ .Values.mongodb.tls.cert | trim }}
    {{ .Values.mongodb.tls.key | trim }}
  {{- end }}
  {{- if .Values.mongodb.tls.caCert }}
  ca.pem: {{ .Values.mongodb.tls.caCert | quote }}
  {{- end }}
  {{- if or .Values.mongodb.tls.clientCert .Values.mongodb.tls.clientKey }}
  client.pem: |
    {{ .Values.mongodb.tls.clientCert | trim }}
    {{ .Values.mongodb.tls.clientKey | trim }}
  {{- end }}
{{- end }}
