{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.mongodbAuthSecret" . }}
  labels:
    app: mongodb
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-root-username: {{ .Values.mongodb.auth.rootUsername | quote }}
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | quote }}
{{- end }}
