{{- if and .Values.mongodb.encryption.enabled (not .Values.mongodb.encryption.existingSecret) .Values.mongodb.encryption.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.mongodbEncryptionSecret" . }}
  labels:
    app: mongodb
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryption.key: {{ .Values.mongodb.encryption.key | quote }}
{{- end }}
