{{- if and .Values.xgt.enabled (not .Values.xgt.license.existingSecret) .Values.xgt.license.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.xgtLicenseSecret" . }}
  labels:
    app: xgt
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  xgtd.lic: {{ .Values.xgt.license.data | quote }}
{{- end }}
