{{- if and .Values.xgt.enabled .Values.xgt.ssl.enabled (not .Values.xgt.ssl.existingSecret) (or .Values.xgt.ssl.cert .Values.xgt.ssl.key .Values.xgt.ssl.caCert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.xgtTlsSecret" . }}
  labels:
    app: xgt
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.xgt.ssl.cert }}
  server.cert.pem: {{ .Values.xgt.ssl.cert | quote }}
  {{- end }}
  {{- if .Values.xgt.ssl.key }}
  server.key.pem: {{ .Values.xgt.ssl.key | quote }}
  {{- end }}
  {{- if .Values.xgt.ssl.caCert }}
  ca-chain.cert.pem: {{ .Values.xgt.ssl.caCert | quote }}
  {{- end }}
{{- end }}
