{{- if and .Values.xgt.enabled .Values.xgt.ldap.enabled (not .Values.xgt.ldap.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketgraph.xgtLdapSecret" . }}
  labels:
    app: xgt
    {{- include "rocketgraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  sssd.conf: |
    {{- if .Values.xgt.ldap.sssdConfig }}
    {{- .Values.xgt.ldap.sssdConfig | nindent 4 }}
    {{- else }}
    [sssd]
    services = nss, pam
    domains = LDAP

    [pam]
    pam_trusted_users = 0

    [domain/LDAP]
    id_provider = ldap
    auth_provider = ldap
    ldap_uri = {{ .Values.xgt.ldap.uri }}
    ldap_search_base = {{ .Values.xgt.ldap.baseDn }}
    {{- if .Values.xgt.ldap.bindDn }}
    ldap_default_bind_dn = {{ .Values.xgt.ldap.bindDn }}
    {{- if .Values.xgt.ldap.bindPassword }}
    ldap_default_authtok = {{ .Values.xgt.ldap.bindPassword }}
    {{- end }}
    {{- end }}
    {{- if .Values.xgt.ldap.startTls }}
    ldap_id_use_start_tls = true
    {{- end }}
    {{- if .Values.xgt.ldap.insecure }}
    ldap_tls_reqcert = never
    ldap_auth_disable_tls_never_use_in_production = true
    {{- end }}
    {{- end }}
{{- end }}
